//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EmployeeDetails
    {
        public T_EmployeeDetails()
        {
            this.T_TimeLog = new HashSet<T_TimeLog>();
        }
    
        public int EmpId { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string BloodGroup { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Pincode { get; set; }
        public int DeptId { get; set; }
    
        public virtual T_DeptDetails T_DeptDetails { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual ICollection<T_TimeLog> T_TimeLog { get; set; }
    }
}
